### ISSUE TITLE
`undefined` uploaded in development

### ISSUE THREAD

**Issue by aandis** [IcarusWorks/ember-cli-deploy-bugsnag#10]
1. `ember deploy development`
1. Sourcemap which gets uploaded is `http://app.comundefined`

**Comment by cafreeman** [comment]
Ditto here. On an Ember 3.4 app

**Comment by cafreeman** [comment]
@aandis I've opened a PR that contains a fix for this [here](https://github.com/IcarusWorks/ember-cli-deploy-bugsnag/pull/11)

**Comment by patrickberkeley** [comment]
@aandis 0.2.0 is out there thanks to @cafreeman's work.

I'm going to close this issue. Let me know if you run into anything.
