### ISSUE TITLE
Version not sent

### ISSUE THREAD

**Issue by byrnedo** [IcarusWorks/ember-cli-deploy-bugsnag#8]
Hi, 

The version doesn't end up being sent to bugsnag. The build itself gets the right version and git is installed in the builder (docker) that runs deploy.

I see the line in the readme about currentVersion but I thought one only has to do that if vcs wasn't available?

ember-cli: 2.15.1

**Comment by jordpo** [comment]
Did you add the [revision-data](https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data) plugin to your deploy pipeline? Currently, this addon checks for the `revisionData` key in the deploy context and if not found, falls back to a Heroku environment variable. 

https://github.com/IcarusWorks/ember-cli-deploy-bugsnag/blob/master/index.js#L30-L36

**Comment by byrnedo** [comment]
Ah! Didn't have that in the pipeline. I'll add it and get back to you.

**Comment by patrickberkeley** [comment]
@byrnedo Did adding the revision-data deploy plugin work for you?

**Comment by byrnedo** [comment]
Worked like a charm! Thanks!
